"""Parser root configuration and exclusion regressions."""

from __future__ import annotations

import os

import pytest

from belief.parser import CodeParser


def _write_func(path, name):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"def {name}():\n    return 1\n", encoding="utf-8")


def test_configured_source_and_corpus_roots_are_scanned_but_rule_roots_are_not(tmp_path):
    _write_func(tmp_path / "src" / "app.py", "app")
    _write_func(tmp_path / "target_flaskjwt" / "case.py", "case")
    _write_func(tmp_path / "security_rules" / "rule.py", "rule")

    parser = CodeParser(
        str(tmp_path),
        source_roots=["src"],
        corpus_roots=["target_flaskjwt"],
        rule_roots=["security_rules"],
    )

    files = {path.relative_to(tmp_path).as_posix() for path in parser._collect_python_files()}

    assert files == {"src/app.py", "target_flaskjwt/case.py"}


def test_docs_are_excluded_by_default_and_included_when_requested(tmp_path):
    _write_func(tmp_path / "src" / "app.py", "app")
    _write_func(tmp_path / "docs" / "sample.py", "sample")

    default_files = {path.relative_to(tmp_path).as_posix() for path in CodeParser(str(tmp_path))._collect_python_files()}
    docs_files = {
        path.relative_to(tmp_path).as_posix()
        for path in CodeParser(str(tmp_path), include_docs=True)._collect_python_files()
    }

    assert default_files == {"src/app.py"}
    assert docs_files == {"docs/sample.py", "src/app.py"}


def test_generated_files_are_skipped(tmp_path):
    generated = tmp_path / "src" / "client_pb2.py"
    generated.parent.mkdir(parents=True)
    generated.write_text("# code generated by protoc. DO NOT EDIT.\ndef generated():\n    return 1\n", encoding="utf-8")
    _write_func(tmp_path / "src" / "real.py", "real")

    files = {path.name for path in CodeParser(str(tmp_path))._collect_python_files()}

    assert files == {"real.py"}


def test_symlink_loop_is_not_followed(tmp_path):
    _write_func(tmp_path / "src" / "real.py", "real")
    link = tmp_path / "src" / "loop"
    try:
        os.symlink(tmp_path, link, target_is_directory=True)
    except OSError:
        pytest.skip("symlinks are unavailable in this Windows test environment")

    files = [path.relative_to(tmp_path).as_posix() for path in CodeParser(str(tmp_path))._collect_python_files()]

    assert files == ["src/real.py"]
